[build]
  publish = "."

[[redirects]]
  from = "/prezzi"
  to = "/prezzi.html"
  status = 200

[[redirects]]
  from = "/download"
  to = "/download.html"
  status = 200

[[redirects]]
  from = "/contatti"
  to = "/contatti.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
